---
- name: build artifacts
  hosts: build
  become: yes

  tasks:
    - name: insure maven is present
      apt:
        name: maven
        state: present
    - name: insure git is present
      apt:
        name: git
        state: presenet
    - name: insure repo is cloned
      ansible.builtin.git:
        dest: /root
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
